[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building entity 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:3.1.0:java (default-cli) @ entity ---
当前时间戳（秒）: 1750172345
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/public/home/blockchain_2/slave2/.m2/repository/org/slf4j/slf4j-reload4j/1.7.36/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/public/home/blockchain_2/slave2/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.17.1/log4j-slf4j-impl-2.17.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Reload4jLoggerFactory]
log4j:WARN No appenders could be found for logger (org.apache.commons.beanutils.converters.BooleanConverter).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
当前时间戳（秒）: 1750172422
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
当前时间戳（秒）: 1750172433
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 1 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
当前时间戳（秒）: 1750172485
Over Processing Init Address


发现 1 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
当前时间戳（秒）: 1750172486
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
当前时间戳（秒）: 1750172486
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
当前时间戳（秒）: 1750172486
org.janusgraph.core.JanusGraphException: Could not execute operation due to backend exception
	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:54)
	at org.janusgraph.diskstorage.BackendTransaction.executeRead(BackendTransaction.java:521)
	at org.janusgraph.diskstorage.BackendTransaction.edgeStoreMultiQuery(BackendTransaction.java:300)
	at org.janusgraph.graphdb.database.StandardJanusGraph.edgeMultiQuery(StandardJanusGraph.java:568)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.lambda$executeMultiQuery$4(StandardJanusGraphTx.java:1252)
	at org.janusgraph.graphdb.query.profile.QueryProfiler.profile(QueryProfiler.java:113)
	at org.janusgraph.graphdb.query.profile.QueryProfiler.profile(QueryProfiler.java:105)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.executeMultiQuery(StandardJanusGraphTx.java:1252)
	at org.janusgraph.graphdb.query.vertex.MultiVertexCentricQueryBuilder.execute(MultiVertexCentricQueryBuilder.java:121)
	at org.janusgraph.graphdb.query.vertex.MultiVertexCentricQueryBuilder.edges(MultiVertexCentricQueryBuilder.java:172)
	at org.janusgraph.graphdb.tinkerpop.optimize.step.fetcher.VertexStepBatchFetcher.makeQueryAndExecute(VertexStepBatchFetcher.java:39)
	at org.janusgraph.graphdb.tinkerpop.optimize.step.fetcher.MultiQueriableStepBatchFetcher.prefetchNextBatch(MultiQueriableStepBatchFetcher.java:112)
	at org.janusgraph.graphdb.tinkerpop.optimize.step.fetcher.MultiQueriableStepBatchFetcher.fetchData(MultiQueriableStepBatchFetcher.java:96)
	at org.janusgraph.graphdb.tinkerpop.optimize.step.JanusGraphVertexStep.flatMap(JanusGraphVertexStep.java:117)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.FlatMapStep.processNextStart(FlatMapStep.java:49)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:140)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:40)
	at org.apache.tinkerpop.gremlin.process.traversal.Traversal.fill(Traversal.java:184)
	at org.apache.tinkerpop.gremlin.process.traversal.Traversal.toList(Traversal.java:122)
	at entity.SG1_dec_base.processInitAddress(SG1_dec_base.java:111)
	at entity.SG1_dec_base.main(SG1_dec_base.java:37)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:279)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.janusgraph.diskstorage.TemporaryBackendException: Could not successfully complete backend operation due to repeated temporary exceptions after PT8M20S
	at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:98)
	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:52)
	... 22 more
Caused by: org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend
	at org.janusgraph.diskstorage.hbase.HBaseKeyColumnValueStore.getHelper(HBaseKeyColumnValueStore.java:230)
	at org.janusgraph.diskstorage.hbase.HBaseKeyColumnValueStore.getSlice(HBaseKeyColumnValueStore.java:119)
	at org.janusgraph.diskstorage.keycolumnvalue.KCVSProxy.getSlice(KCVSProxy.java:87)
	at org.janusgraph.diskstorage.keycolumnvalue.cache.ExpirationKCVSCache.getSlice(ExpirationKCVSCache.java:122)
	at org.janusgraph.diskstorage.BackendTransaction$2.call(BackendTransaction.java:303)
	at org.janusgraph.diskstorage.BackendTransaction$2.call(BackendTransaction.java:300)
	at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:66)
	... 23 more
Caused by: org.apache.hadoop.hbase.client.RetriesExhaustedException: Failed after attempts=16, exceptions:
2025-06-17T15:02:32.152Z, RpcRetryingCaller{globalStartTime=2025-06-17T15:01:31.859Z, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.CallTimeoutException: Call to address=node11:16020 failed on local exception: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call[id=122,methodName=Get], waitTime=60232ms, rpcTimeout=60000ms
2025-06-17T15:03:32.271Z, RpcRetryingCaller{globalStartTime=2025-06-17T15:01:31.859Z, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.CallTimeoutException: Call to address=node11:16020 failed on local exception: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call[id=138,methodName=Get], waitTime=60008ms, rpcTimeout=60000ms
2025-06-17T15:04:32.481Z, RpcRetryingCaller{globalStartTime=2025-06-17T15:01:31.859Z, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.CallTimeoutException: Call to address=node11:16020 failed on local exception: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call[id=154,methodName=Get], waitTime=60002ms, rpcTimeout=60000ms
2025-06-17T15:05:32.802Z, RpcRetryingCaller{globalStartTime=2025-06-17T15:01:31.859Z, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.CallTimeoutException: Call to address=node11:16020 failed on local exception: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call[id=170,methodName=Get], waitTime=60011ms, rpcTimeout=60000ms
2025-06-17T15:06:33.501Z, RpcRetryingCaller{globalStartTime=2025-06-17T15:01:31.859Z, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.CallTimeoutException: Call to address=node11:16020 failed on local exception: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call[id=186,methodName=Get], waitTime=60188ms, rpcTimeout=60000ms
2025-06-17T15:07:34.511Z, RpcRetryingCaller{globalStartTime=2025-06-17T15:01:31.859Z, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.CallTimeoutException: Call to address=node11:16020 failed on local exception: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call[id=203,methodName=Get], waitTime=60002ms, rpcTimeout=60000ms
2025-06-17T15:08:37.214Z, RpcRetryingCaller{globalStartTime=2025-06-17T15:01:31.859Z, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.CallTimeoutException: Call to address=node11:16020 failed on local exception: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call[id=219,methodName=Get], waitTime=60010ms, rpcTimeout=60000ms
2025-06-17T15:09:41.232Z, RpcRetryingCaller{globalStartTime=2025-06-17T15:01:31.859Z, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.CallTimeoutException: Call to address=node11:16020 failed on local exception: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call[id=236,methodName=Get], waitTime=60009ms, rpcTimeout=60000ms
2025-06-17T15:10:51.262Z, RpcRetryingCaller{globalStartTime=2025-06-17T15:01:31.859Z, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.CallTimeoutException: Call to address=node11:16020 failed on local exception: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call[id=254,methodName=Get], waitTime=60004ms, rpcTimeout=60000ms
2025-06-17T15:12:01.292Z, RpcRetryingCaller{globalStartTime=2025-06-17T15:01:31.859Z, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.CallTimeoutException: Call to address=node11:16020 failed on local exception: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call[id=272,methodName=Get], waitTime=60003ms, rpcTimeout=60000ms
2025-06-17T15:13:11.402Z, RpcRetryingCaller{globalStartTime=2025-06-17T15:01:31.859Z, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.CallTimeoutException: Call to address=node11:16020 failed on local exception: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call[id=290,methodName=Get], waitTime=60009ms, rpcTimeout=60000ms
2025-06-17T15:14:21.452Z, RpcRetryingCaller{globalStartTime=2025-06-17T15:01:31.859Z, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.CallTimeoutException: Call to address=node11:16020 failed on local exception: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call[id=308,methodName=Get], waitTime=60008ms, rpcTimeout=60000ms
2025-06-17T15:15:41.542Z, RpcRetryingCaller{globalStartTime=2025-06-17T15:01:31.859Z, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.CallTimeoutException: Call to address=node11:16020 failed on local exception: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call[id=328,methodName=Get], waitTime=60005ms, rpcTimeout=60000ms
2025-06-17T15:17:01.672Z, RpcRetryingCaller{globalStartTime=2025-06-17T15:01:31.859Z, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.CallTimeoutException: Call to address=node11:16020 failed on local exception: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call[id=348,methodName=Get], waitTime=60003ms, rpcTimeout=60000ms
2025-06-17T15:18:21.812Z, RpcRetryingCaller{globalStartTime=2025-06-17T15:01:31.859Z, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.CallTimeoutException: Call to address=node11:16020 failed on local exception: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call[id=368,methodName=Get], waitTime=60005ms, rpcTimeout=60000ms
2025-06-17T15:19:41.831Z, RpcRetryingCaller{globalStartTime=2025-06-17T15:01:31.859Z, pause=100, maxAttempts=16}, org.apache.hadoop.hbase.ipc.CallTimeoutException: Call to address=node11:16020 failed on local exception: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call[id=388,methodName=Get], waitTime=60007ms, rpcTimeout=60000ms

	at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:141)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:390)
	at org.apache.hadoop.hbase.client.HTable.lambda$get$0(HTable.java:363)
	at org.apache.hadoop.hbase.trace.TraceUtil.trace(TraceUtil.java:216)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:363)
	at org.apache.hadoop.hbase.client.HTable.lambda$get$1(HTable.java:409)
	at org.apache.hadoop.hbase.trace.TraceUtil.trace(TraceUtil.java:216)
	at org.apache.hadoop.hbase.client.HTable.get(HTable.java:407)
	at org.janusgraph.diskstorage.hbase.HBaseKeyColumnValueStore.getHelper(HBaseKeyColumnValueStore.java:198)
	... 29 more
Caused by: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call to address=node11:16020 failed on local exception: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call[id=388,methodName=Get], waitTime=60007ms, rpcTimeout=60000ms
	at org.apache.hadoop.hbase.ipc.IPCUtil.wrapException(IPCUtil.java:222)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.onCallFinished(AbstractRpcClient.java:392)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.access$100(AbstractRpcClient.java:92)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:426)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$3.run(AbstractRpcClient.java:421)
	at org.apache.hadoop.hbase.ipc.Call.setTimeout(Call.java:107)
	at org.apache.hadoop.hbase.ipc.RpcConnection$1.run(RpcConnection.java:134)
	at org.apache.hbase.thirdparty.io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at org.apache.hbase.thirdparty.io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at org.apache.hbase.thirdparty.io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at org.apache.hbase.thirdparty.io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at org.apache.hbase.thirdparty.io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	... 1 more
Caused by: org.apache.hadoop.hbase.ipc.CallTimeoutException: Call[id=388,methodName=Get], waitTime=60007ms, rpcTimeout=60000ms
	at org.apache.hadoop.hbase.ipc.RpcConnection$1.run(RpcConnection.java:135)
	... 6 more
Over Processing Init Address


发现 1 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
当前时间戳（秒）: 1750173649
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
当前时间戳（秒）: 1750173649
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
当前时间戳（秒）: 1750173654
Over Processing Init Address


发现 0 个匹配组：
Over Processing Init Address


发现 0 个匹配组：
当前时间戳（秒）: 1750173654
[WARNING] thread Thread[Idle-Rpc-Conn-Sweeper-pool-0,5,entity.SG1_dec_base] was interrupted but is still alive after waiting at least 14999msecs
[WARNING] thread Thread[Idle-Rpc-Conn-Sweeper-pool-0,5,entity.SG1_dec_base] will linger despite being asked to die via interruption
[WARNING] thread Thread[RPCClient-NioEventLoopGroup-1-1,5,entity.SG1_dec_base] will linger despite being asked to die via interruption
[WARNING] thread Thread[RpcClient-timer-pool-0,5,entity.SG1_dec_base] will linger despite being asked to die via interruption
[WARNING] thread Thread[RPCClient-NioEventLoopGroup-1-2,5,entity.SG1_dec_base] will linger despite being asked to die via interruption
[WARNING] thread Thread[RPCClient-NioEventLoopGroup-1-3,5,entity.SG1_dec_base] will linger despite being asked to die via interruption
[WARNING] thread Thread[RPCClient-NioEventLoopGroup-1-4,5,entity.SG1_dec_base] will linger despite being asked to die via interruption
[WARNING] thread Thread[RPCClient-NioEventLoopGroup-1-5,5,entity.SG1_dec_base] will linger despite being asked to die via interruption
[WARNING] thread Thread[RPCClient-NioEventLoopGroup-1-6,5,entity.SG1_dec_base] will linger despite being asked to die via interruption
[WARNING] thread Thread[RPCClient-NioEventLoopGroup-1-7,5,entity.SG1_dec_base] will linger despite being asked to die via interruption
[WARNING] thread Thread[RPCClient-NioEventLoopGroup-1-8,5,entity.SG1_dec_base] will linger despite being asked to die via interruption
[WARNING] thread Thread[RPCClient-NioEventLoopGroup-1-9,5,entity.SG1_dec_base] will linger despite being asked to die via interruption
[WARNING] thread Thread[ForkJoinPool.commonPool-worker-0,5,entity.SG1_dec_base] will linger despite being asked to die via interruption
[WARNING] thread Thread[RPCClient-NioEventLoopGroup-1-10,5,entity.SG1_dec_base] will linger despite being asked to die via interruption
[WARNING] thread Thread[ForkJoinPool.commonPool-worker-25,5,entity.SG1_dec_base] will linger despite being asked to die via interruption
[WARNING] thread Thread[RPCClient-NioEventLoopGroup-1-11,5,entity.SG1_dec_base] will linger despite being asked to die via interruption
[WARNING] NOTE: 15 thread(s) did not finish despite being asked to via interruption. This is not a problem with exec:java, it is a problem with the running code. Although not serious, it should be remedied.
[WARNING] Couldn't destroy threadgroup org.codehaus.mojo.exec.ExecJavaMojo$IsolatedThreadGroup[name=entity.SG1_dec_base,maxpri=10]
java.lang.IllegalThreadStateException
	at java.lang.ThreadGroup.destroy(ThreadGroup.java:778)
	at org.codehaus.mojo.exec.ExecJavaMojo.execute(ExecJavaMojo.java:319)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 23:12 min
[INFO] Finished at: 2025-06-17T23:21:12+08:00
[INFO] Final Memory: 63M/11709M
[INFO] ------------------------------------------------------------------------
